# Generated by Django 5.0.3 on 2024-04-04 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='Mã học sinh')),
                ('name', models.CharField(max_length=255, verbose_name='Tên học sinh')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(12)], verbose_name='Khối')),
                ('classroom', models.CharField(max_length=255, verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Môn học')),
                ('score', models.FloatField(verbose_name='Điểm')),
                ('score_type', models.CharField(choices=[('15m', '15 phút'), ('hk', 'Học kỳ'), ('thi', 'Thi')], default='15m', max_length=10, verbose_name='Loại điểm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student', verbose_name='Học sinh')),
            ],
        ),
    ]
